
jimmy_test_group:
  parent_groups:
  - managed_ubuntu
  playbooks:
  - jimmy_test_group.yml
managed_oraclelinux:
  parent_groups:
  - base_oraclelinux
  playbooks:
  - managed-system-customization.yml

